name: Laravel Deploy

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Deploy para Produção
      uses: appleboy/ssh-action@master
      with:
        username: USER NAME DO SERVIDOR AQUI
        host: NOME DO HOST AQUI
        password: ${{ secrets.SSH_PASSWORD }}
        #CASO FOR UTILIZAR CONEXÃO VIA SSH, DESCOMENTE O CAMPO ABAIXO E COMENTE O CAMPO ACIMA
        #key: KEY SSH AQUI
        script: |
          cd /var/www/html/NOME_APLICACAO
          php artisan down
          git pull origin main
          composer install
          php artisan migrate --seed
          service supervisor restart
          php artisan view:clear
          php artisan up
